// Emacs style mode select   -*- C++ -*-
//-----------------------------------------------------------------------------
//
// $Id: info.h,v 1.3 2000/04/04 00:32:46 stroggonmeth Exp $
//
// Copyright (C) 1993-1996 by id Software, Inc.
// Portions Copyright (C) 1998-2000 by DooM Legacy Team.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// $Log: info.h,v $
// Revision 1.3  2000/04/04 00:32:46  stroggonmeth
// Initial Boom compatability plus few misc changes all around.
//
// Revision 1.2  2000/02/27 00:42:10  hurdler
// fix CR+LF problem
//
// Revision 1.1.1.1  2000/02/22 20:32:32  hurdler
// Initial import into CVS (v1.29 pr3)
//
//
// DESCRIPTION:
//      Thing frame/state LUT,
//      generated by multigen utilitiy.
//      This one is the original DOOM version, preserved.
//
//-----------------------------------------------------------------------------

#ifndef __INFO__
#define __INFO__

// Needed for action function pointer handling.
#include "d_think.h"

typedef enum
{
	// srb2-nozomi color consts
	SKINCOLOR_WHITE,
	SKINCOLOR_SILVER,
	SKINCOLOR_GREY,
	SKINCOLOR_PINK,
	SKINCOLOR_CHERRYBLOSSOM,
	SKINCOLOR_BRIGHTRED,
	SKINCOLOR_RED,
	SKINCOLOR_CRIMSON,
	SKINCOLOR_PEACH,
	SKINCOLOR_APRICOT,
	SKINCOLOR_BEIGE,
	SKINCOLOR_LEMON,
	SKINCOLOR_GREEN,
	SKINCOLOR_FOREST,
	SKINCOLOR_LIGHTBLUE,
	SKINCOLOR_BLUE,
	SKINCOLOR_DEEPBLUE,
	SKINCOLOR_PURPLE,
	SKINCOLOR_LEGACYARMY,
	MAXSKINCOLORS
} skincolornum_t;

extern char *Color_Names[MAXSKINCOLORS+1];

typedef enum
{
    SPR_NULL,
    SPR_PLAY,
    SPR_POSS,
    SPR_SPOS,
    SPR_EGGM,
    SPR_MISL,
    SPR_BON1,
    SPR_STIM,
    SPR_MEDI,
    SPR_EMMY,
    SPR_PINV,
    SPR_GRTV,
    SPR_POL2,
    SPR_SHTV,
    SPR_COL3,
    SPR_BUBL,
    SPR_BLTV,
    SPR_YLTV,
    SPR_COL5,
    SPR_POB1,
    SPR_SMOK,
    SPR_SPLA,
    SPR_BIRD,
    SPR_SQRL,
    SPR_BORB,
    SPR_YORB,
    SPR_GORB,
    SPR_KORB,
    SPR_SPRK,
    SPR_IVSP,
    SPR_IVSQ,
    SPR_BUBP,
    SPR_BUBO,
    SPR_BUBN,
    SPR_BUBM,
    SPR_CNTA,
    SPR_CNTB,
    SPR_CNTC,
    SPR_CNTD,
    SPR_CNTE,
    SPR_CNTF,
    SPR_POPP,
    SPR_PRUP,
    SPR_BKTV,
    SPR_SCRA,
    SPR_SCRB,
    SPR_SCRC,
    SPR_SCRD,
    SPR_SSPK,
    SPR_GRAS,
    SPR_YSPR,
    SPR_RSPR,
    SPR_BSPR,
    SPR_SKIM,
    SPR_MINE,
    SPR_FISH,
    SPR_GARG,
    SPR_SPLH,
    SPR_GTHO,
    SPR_GRTH,
    SPR_PCTH,
    SPR_DRTH,
    SPR_STHO,
    SPR_OTHO,
    SPR_RTHO,
    SPR_BTHO,
    SPR_PTHO,
    SPR_DBTH,
    SPR_BGTH,
    SPR_THZP,
    SPR_SIGN,
    SPR_RRNG,
    SPR_TTAG,
    SPR_STEM,
    SPR_RFLG,
    SPR_BFLG,
    SPR_GFLG,
    SPR_TOKE,
    SPR_CEMG,
    SPR_CEMO,
    SPR_CEMP,
    SPR_CEMB,
    SPR_CEMR,
    SPR_CEML,
    SPR_CEMY,
    SPR_JETB,
    SPR_JETG,
    SPR_JBUL,
    SPR_MOUS,
    SPR_DETN,
    SPR_XPLD,
    SPR_REDX,
    SPR_CHAN,
    SPR_CAPE,
    SPR_SNO1,
    SPR_SANT,
    SPR_EMER,
    SPR_EMES,
    SPR_EMET,
    SPR_SBLL,
    SPR_SPIK,
    SPR_CCOM,
    SPR_MARL,
    SPR_RAIN,
    SPR_NSPR,
	NUMSPRITES

} spritenum_t;

typedef enum
{
    S_NULL,
    S_PLAY,
    S_PLAY_TAP1, // Tails 12-03-99
    S_PLAY_TAP2, // Tails 12-03-99
    S_PLAY_RUN1,
    S_PLAY_RUN2,
    S_PLAY_RUN3,
    S_PLAY_RUN4,
    S_PLAY_RUN5, // Tails 9-14-99
    S_PLAY_RUN6, // Tails 9-14-99
    S_PLAY_RUN7, // Tails 9-14-99
    S_PLAY_RUN8, // Tails 9-14-99
    S_PLAY_ATK1, // Tails 9-14-99
    S_PLAY_ATK2, // Tails 9-14-99
    S_PLAY_ATK3, // Tails 9-14-99
    S_PLAY_ATK4, // Tails 9-14-99
    S_PLAY_PLG1, // Tails 9-14-99
    S_PLAY_SPD1, // Tails 03-02-2000
    S_PLAY_SPD2, // Tails 03-02-2000
    S_PLAY_SPD3, // Tails 03-02-2000
    S_PLAY_SPD4, // Tails 03-02-2000
    S_PLAY_ABL1, // Tails 03-02-2000
    S_PLAY_ABL2, // Tails 03-02-2000
    S_PLAY_SPC1, // Tails 03-02-2000
    S_PLAY_SPC2, // Tails 03-02-2000 ---- Finalized the character spec
    S_PLAY_SPC3, // Tails 03-02-2000
    S_PLAY_SPC4, // Tails 03-02-2000
	S_PLAY_CLIMB1, // Tails 01-03-2001
	S_PLAY_CLIMB2, // Tails 01-03-2001
	S_PLAY_CLIMB3, // Tails 01-03-2001
	S_PLAY_CLIMB4, // Tails 01-03-2001
	S_PLAY_CLIMB5, // Tails 01-03-2001
    S_PLAY_GASP, // Tails 03-02-2000
    S_PLAY_PAIN, // Tails 03-02-2000
    S_PLAY_DIE1, // Tails 03-02-2000
    S_PLAY_DIE2, // Tails 03-02-2000
    S_PLAY_DIE3, // Tails 03-02-2000
    S_PLAY_TEETER1, // Tails 03-02-2000
    S_PLAY_TEETER2, // Tails 03-02-2000
	S_PLAY_FALL1, // Tails 03-02-2000
	S_PLAY_FALL2, // Tails 03-02-2000
// New Crawla Animations Tails 06-13-2000
    S_POSS_STND,
    S_POSS_STND2,
    S_POSS_RUN1,
    S_POSS_RUN2,
    S_POSS_RUN3,
    S_POSS_RUN4,
    S_POSS_RUN5,
    S_POSS_RUN6,
    S_POSS_RUN7,
    S_POSS_RUN8,
    S_POSS_RUN9,
    S_POSS_RUN10,
    S_POSS_RUN11,
    S_POSS_RUN12,
    S_POSS_RUN13,
    S_POSS_RUN14,
    S_POSS_RUN15,
    S_POSS_RUN16,
    S_POSS_RUN17,
    S_POSS_DIE1,
    S_POSS_DIE2,
    S_POSS_DIE3,
    S_POSS_DIE4,
// XDIE frames deleted Tails 10-25-99
// New Crawla Animations Tails 06-13-2000
    S_SPOS_STND,
    S_SPOS_STND2,
    S_SPOS_RUN1,
    S_SPOS_RUN2,
    S_SPOS_RUN3,
    S_SPOS_RUN4,
    S_SPOS_RUN5,
    S_SPOS_RUN6,
    S_SPOS_RUN7,
    S_SPOS_RUN8,
    S_SPOS_RUN9,
    S_SPOS_RUN10,
    S_SPOS_RUN11,
    S_SPOS_RUN12,
    S_SPOS_RUN13,
    S_SPOS_RUN14,
    S_SPOS_RUN15,
    S_SPOS_RUN16,
    S_SPOS_RUN17,
    S_SPOS_DIE1,
    S_SPOS_DIE2,
    S_SPOS_DIE3,
    S_SPOS_DIE4,
    S_EGGMOBILE_STND, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_STND2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_RUN1, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_RUN2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_RUN3, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_RUN4, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_ATK1, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_ATK2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN3, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN4, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN5, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN6, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN7, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN8, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN9, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN10, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN11, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN12, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE1, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE3, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE4, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE5, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE6, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE7, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE8, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE9, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE10, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE11, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE12, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE13, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE14, // Boss 1 Tails 11-29-99
    S_ROCKET,
    S_EXPLODE1,
    S_EXPLODE2,
    S_EXPLODE3,
    S_BON1,
    S_BON1A,
    S_BON1B,
    S_BON1C,
    S_BON1D,
    S_BON1E,
    S_BON1F, //Tails 9-15-99
    S_BON1G, //Tails 9-15-99
    S_BON1H, //Tails 9-15-99
    S_BON1I, //Tails 9-15-99
    S_BON1J, //Tails 9-15-99
    S_BON1K, //Tails 9-15-99
    S_BON1L, //Tails 9-15-99
    S_BON1M, //Tails 9-15-99
    S_BON1N, //Tails 9-15-99
    S_BON1O,  //Tails 9-15-99
    S_BON1P,  //Tails 10-29-99
    S_BON1Q,  //Tails 10-29-99
    S_BON1R,  //Tails 10-29-99
    S_BON1S,  //Tails 10-29-99
    S_BON1T,  //Tails 10-29-99
    S_BON1U,  //Tails 10-29-99
    S_BON1V,  //Tails 10-29-99
    S_BON1W,  //Tails 10-29-99
    S_STIM,
    S_STIM1, // Tails 9-30-99
    S_STIM2, // Tails 9-30-99
    S_STIM3, // Tails 9-30-99
    S_STIM4, // Tails 9-30-99
    S_STIM5, // Tails 9-30-99
    S_STIM6, // Tails 9-30-99
    S_STIM7, // Tails 9-30-99
    S_STIM8, // Tails 2-13-00
    S_MEDI,
    S_MEDI1, // Tails 9-30-99
    S_MEDI2, // Tails 9-30-99
    S_MEDI3, // Tails 9-30-99
    S_MEDI4, // Tails 9-30-99
    S_MEDI5, // Tails 9-30-99
    S_MEDI6, // Tails 9-30-99
    S_MEDI7, // Tails 9-30-99
    S_MEDI8, // Tails 2-13-00
    S_EMMY1, // start emerald tails
    S_EMMY2,
    S_EMMY3,
    S_EMMY4,
    S_EMMY5,
    S_EMMY6,
    S_EMMY7, // end emerald tails
    S_PINV, // start invincibility box tails
    S_PINV2,
    S_PINV3,
    S_PINV4,
    S_PINV5,
    S_PINV6,
    S_PINV7,
    S_PINV8,
    S_PINV9, // end invincibility box tails
    S_GRTV, // Tails 9-30-99
    S_GRTV1, // Tails 9-30-99
    S_GRTV2, // Tails 9-30-99
    S_GRTV3, // Tails 9-30-99
    S_GRTV4, // Tails 9-30-99
    S_GRTV5, // Tails 9-30-99
    S_GRTV6, // Tails 9-30-99
    S_GRTV7, // Tails 9-30-99
    S_GRTV8, // Tails 2-13-00
    S_HEADSONSTICK,
    S_HEADSONSTICK2, // Tails 11-06-99
    S_HEADSONSTICK3, // Tails 11-06-99
    S_HEADSONSTICK4, // Tails 11-06-99
    S_HEADSONSTICK5, // Tails 11-06-99
    S_HEADSONSTICK6, // Tails 11-06-99
    S_HEADSONSTICK7, // Tails 11-06-99
    S_HEADSONSTICK8, // Tails 11-06-99
    S_SHTV, // Tails 9-30-99
    S_SHTV1, // Tails 9-30-99
    S_SHTV2, // Tails 9-30-99
    S_SHTV3, // Tails 9-30-99
    S_SHTV4, // Tails 9-30-99
    S_SHTV5, // Tails 9-30-99
    S_SHTV6, // Tails 9-30-99
    S_SHTV7, // Tails 9-30-99
    S_SHTV8, // Tails 2-13-00
    S_TALLREDCOL, // It's da fan! Tails 12-05-99
    S_TALLREDCOL2, // It's da fan! Tails 12-05-99
    S_TALLREDCOL3, // It's da fan! Tails 12-05-99
    S_TALLREDCOL4, // It's da fan! Tails 12-05-99
    S_TALLREDCOL5, // It's da fan! Tails 12-05-99
	S_TALLREDCOL6, // It's da Red fan! Nozomi 03-15-26
	S_TALLREDCOL7, // It's da Red fan! Nozomi 03-15-26
	S_TALLREDCOL8, // It's da Red fan! Nozomi 03-15-26
	S_TALLREDCOL9, // It's da Red fan! Nozomi 03-15-26
	S_TALLREDCOL10, // It's da Red fan! Nozomi 03-15-26
    S_BUBBLES1, // Bubble Source Tails 03-07-2000
    S_BUBBLES2, // Bubble Source Tails 03-07-2000
    S_BLTV, // Tails 9-30-99
    S_BLTV1, // Tails 9-30-99
    S_BLTV2, // Tails 9-30-99
    S_BLTV3, // Tails 9-30-99
    S_BLTV4, // Tails 9-30-99
    S_BLTV5, // Tails 9-30-99
    S_BLTV6, // Tails 9-30-99
    S_BLTV7, // Tails 9-30-99
    S_BLTV8, // Tails 2-13-00
    S_YLTV, // Tails 9-30-99
    S_YLTV1, // Tails 9-30-99
    S_YLTV2, // Tails 9-30-99
    S_YLTV3, // Tails 9-30-99
    S_YLTV4, // Tails 9-30-99
    S_YLTV5, // Tails 9-30-99
    S_YLTV6, // Tails 9-30-99
    S_YLTV7, // Tails 9-30-99
    S_YLTV8, // Tails 2-13-00
    S_HEARTCOL,
    S_HEARTCOL2,
    S_COLONGIBS,
    S_COLONGIBS2, // Tails 11-07-99
    S_COLONGIBS3, // Tails 11-07-99
    S_COLONGIBS4, // Tails 11-07-99
    S_COLONGIBS5, // Tails 11-07-99
    S_COLONGIBS6, // Tails 11-07-99
    S_COLONGIBS7, // Tails 11-07-99
    S_COLONGIBS8, // Tails 11-07-99
    //Fab: added lava/slime damage burn smoke
    S_SMOK1,
    S_SMOK2,
    S_SMOK3,
    S_SMOK4,
    S_SMOK5,
    //Fab: added water splash
    S_SPLASH1,
    S_SPLASH2,
    S_SPLASH3,
	S_BIRD1, // Tails 10-20-99 Birdie free!
    S_BIRD2, // Tails 10-20-99 Birdie free!
    S_BIRD3, // Tails 10-23-99 Birdie free!
    S_SQRL1, // Tails 10-20-99 Squirrel free!
    S_SQRL2, // Tails 10-20-99 Squirrel free!
    S_SQRL3, // Tails 10-23-99 Squirrel free!
    S_SQRL4, // Tails 10-20-99 Squirrel free!
    S_SQRL5, // Tails 10-20-99 Squirrel free!
    S_SQRL6, // Tails 10-20-99 Squirrel free!
    S_SQRL7, // Tails 10-20-99 Squirrel free!
    S_SQRL8, // Tails 10-20-99 Squirrel free!
    S_SQRL9, // Tails 10-20-99 Squirrel free!
    S_SQRL10, // Tails 10-20-99 Squirrel free!
    S_BORB1, // Tails 12-29-99 shield mobjs
    S_BORB2, // Tails 12-29-99 shield mobjs
    S_BORB3, // Tails 12-29-99 shield mobjs
    S_BORB4, // Tails 12-29-99 shield mobjs
    S_BORB5, // Tails 12-29-99 shield mobjs
    S_BORB6, // Tails 12-29-99 shield mobjs
    S_BORB7, // Tails 12-29-99 shield mobjs
    S_BORB8, // Tails 12-29-99 shield mobjs
    S_YORB1, // Tails 12-29-99 shield mobjs
    S_YORB2, // Tails 12-29-99 shield mobjs
    S_YORB3, // Tails 12-29-99 shield mobjs
    S_YORB4, // Tails 12-29-99 shield mobjs
    S_YORB5, // Tails 12-29-99 shield mobjs
    S_YORB6, // Tails 12-29-99 shield mobjs
    S_YORB7, // Tails 12-29-99 shield mobjs
    S_YORB8, // Tails 12-29-99 shield mobjs
    S_GORB1, // Tails 12-29-99 shield mobjs
    S_GORB2, // Tails 06-28-2000 shield mobjs
    S_GORB3, // Tails 06-28-2000 shield mobjs
    S_GORB4, // Tails 06-28-2000 shield mobjs
    S_GORB5, // Tails 06-28-2000 shield mobjs
    S_GORB6, // Tails 06-28-2000 shield mobjs
    S_GORB7, // Tails 06-28-2000 shield mobjs
    S_GORB8, // Tails 06-28-2000 shield mobjs
    S_KORB1, // Tails 12-29-99 shield mobjs
    S_KORB2, // Tails 12-29-99 shield mobjs
    S_KORB3, // Tails 12-29-99 shield mobjs
    S_KORB4, // Tails 12-29-99 shield mobjs
    S_KORB5, // Tails 12-29-99 shield mobjs
    S_KORB6, // Tails 12-29-99 shield mobjs
    S_KORB7, // Tails 12-29-99 shield mobjs
    S_KORB8, // Tails 12-29-99 shield mobjs
    S_SPRK1, // spark start tails
    S_SPRK2,
    S_SPRK3,
    S_SPRK4,
    S_SPRK5, // spark
    S_SPRK6,
    S_SPRK7,
    S_SPRK8,
    S_SPRK9, // spark
    S_SPRK10,
    S_SPRK11,
    S_SPRK12,
    S_SPRK13, // spark
    S_SPRK14,
    S_SPRK15,
    S_SPRK16, // end spark tails
    S_IVSP1, // invincibility sparkles tails
    S_IVSP2, // invincibility sparkles tails
    S_IVSP3, // invincibility sparkles tails
    S_IVSP4, // invincibility sparkles tails
    S_IVSP5, // invincibility sparkles tails
    S_IVSP6, // invincibility sparkles tails
    S_IVSP7, // invincibility sparkles tails
    S_IVSP8, // invincibility sparkles tails
    S_IVSP9, // invincibility sparkles tails
    S_IVSP10, // invincibility sparkles tails
    S_IVSP11, // invincibility sparkles tails
    S_IVSP12, // invincibility sparkles tails
    S_IVSP13, // invincibility sparkles tails
    S_IVSP14, // invincibility sparkles tails
    S_IVSP15, // invincibility sparkles tails
    S_IVSP16, // invincibility sparkles tails
    S_IVSP17, // invincibility sparkles tails
    S_IVSP18, // invincibility sparkles tails
    S_IVSP19, // invincibility sparkles tails
    S_IVSP20, // invincibility sparkles tails
    S_IVSP21, // invincibility sparkles tails
    S_IVSP22, // invincibility sparkles tails
    S_IVSP23, // invincibility sparkles tails
    S_IVSP24, // invincibility sparkles tails
    S_IVSP25, // invincibility sparkles tails
    S_IVSP26, // invincibility sparkles tails
    S_IVSP27, // invincibility sparkles tails
    S_IVSP28, // invincibility sparkles tails
    S_IVSP29, // invincibility sparkles tails
    S_IVSQ1, // invincibility sparkles finish tails
    S_IVSQ2, // invincibility sparkles finish tails
    S_IVSQ3, // invincibility sparkles finish tails
    S_DISS, // dissipating object tails
    S_SMALLBUBBLE, // small bubble Tails 03-07-2000
    S_SMALLBUBBLE1, // small bubble Tails 03-07-2000
    S_MEDIUMBUBBLE, // medium bubble Tails 03-07-2000
    S_MEDIUMBUBBLE1, // medium bubble Tails 03-07-2000
    S_LARGEBUBBLE, // large bubble Tails 03-07-2000
    S_EXTRALARGEBUBBLE, // extra large bubble (breathable) Tails 03-07-2000
    S_EXTRALARGEBUBBLE1, // extra large bubble (breathable) Tails 03-07-2000
    S_ZERO1, // Drowning Timer - 0 Tails 03-07-2000
    S_ONE1, // Drowning Timer - 1 Tails 03-07-2000
    S_TWO1, // Drowning Timer - 2 Tails 03-07-2000
    S_THREE1, // Drowning Timer - 3 Tails 03-07-2000
    S_FOUR1, // Drowning Timer - 4 Tails 03-07-2000
    S_FIVE1, // Drowning Timer - 5 Tails 03-07-2000
    S_POP1, // Extra Large bubble goes POP! Tails 03-08-2000
    S_PRUP1, // 1Up box Tails 03-12-2000
    S_PRUP2, // 1Up box Tails 03-12-2000
    S_PRUP3, // 1Up box Tails 03-12-2000
    S_PRUP4, // 1Up box Tails 03-12-2000
    S_PRUP5, // 1Up box Tails 03-12-2000
    S_PRUP6, // 1Up box Tails 03-12-2000
    S_PRUP7, // 1Up box Tails 03-12-2000
    S_PRUP8, // 1Up box Tails 03-12-2000
    S_PRUP9, // 1Up box Tails 03-12-2000
    S_BKTV1, // Black shield TV Tails 04-08-2000
    S_BKTV2, // Black shield TV Tails 04-08-2000
    S_BKTV3, // Black shield TV Tails 04-08-2000
    S_BKTV4, // Black shield TV Tails 04-08-2000
    S_BKTV5, // Black shield TV Tails 04-08-2000
    S_BKTV6, // Black shield TV Tails 04-08-2000
    S_BKTV7, // Black shield TV Tails 04-08-2000
    S_BKTV8, // Black shield TV Tails 04-08-2000
    S_BKTV9, // Black shield TV Tails 04-08-2000
    S_SCRA, // 100 score logo Tails 04-16-2000
    S_SCRA2, // 100 score logo Tails 04-16-2000
    S_SCRB, // 200 score logo Tails 04-16-2000
    S_SCRB2, // 200 score logo Tails 04-16-2000
    S_SCRC, // 500 score logo Tails 04-16-2000
    S_SCRC2, // 500 score logo Tails 04-16-2000
    S_SCRD, // 1000 score logo Tails 04-16-2000
    S_SCRD2, // 1000 score logo Tails 04-16-2000
    S_SSPK1, // Super Sonic Spark Tails 04-18-2000
    S_SSPK2, // Super Sonic Spark Tails 04-18-2000
    S_SSPK3, // Super Sonic Spark Tails 04-18-2000
    S_SSPK4, // Super Sonic Spark Tails 04-18-2000
    S_SSPK5, // Super Sonic Spark Tails 04-18-2000
    S_GRASS1, // Grass debris Tails 05-14-2000
    S_GRASS2, // Grass debris Tails 05-14-2000
    S_GRASS3, // Grass debris Tails 05-14-2000
    S_GRASS4, // Grass debris Tails 05-14-2000
    S_GRASS5, // Grass debris Tails 05-14-2000
    S_GRASS6, // Grass debris Tails 05-14-2000
    S_GRASS7, // Grass debris Tails 05-14-2000
    S_YDIAG1, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG2, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG3, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG4, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG5, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG6, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG7, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG8, // Yellow Diagonal Spring Tails 05-17-2000
    S_AWATERA1, // Ambient Water Sound 1 Tails 06-10-2000
    S_AWATERA2, // Ambient Water Sound 1 Tails 06-10-2000
    S_AWATERB1, // Ambient Water Sound 2 Tails 06-10-2000
    S_AWATERB2, // Ambient Water Sound 2 Tails 06-10-2000
    S_AWATERC1, // Ambient Water Sound 3 Tails 06-10-2000
    S_AWATERC2, // Ambient Water Sound 3 Tails 06-10-2000
    S_AWATERD1, // Ambient Water Sound 4 Tails 06-10-2000
    S_AWATERD2, // Ambient Water Sound 4 Tails 06-10-2000
    S_AWATERE1, // Ambient Water Sound 5 Tails 06-10-2000
    S_AWATERE2, // Ambient Water Sound 5 Tails 06-10-2000
    S_AWATERF1, // Ambient Water Sound 6 Tails 06-10-2000
    S_AWATERF2, // Ambient Water Sound 6 Tails 06-10-2000
    S_AWATERG1, // Ambient Water Sound 7 Tails 06-10-2000
    S_AWATERG2, // Ambient Water Sound 7 Tails 06-10-2000
    S_AWATERH1, // Ambient Water Sound 8 Tails 06-10-2000
    S_AWATERH2, // Ambient Water Sound 8 Tails 06-10-2000
    S_SKIM1, // Skim mine dropper Tails 06-13-2000
    S_SKIM2, // Skim mine dropper Tails 06-13-2000
    S_SKIM3, // Skim mine dropper Tails 06-13-2000
    S_SKIM4, // Skim mine dropper Tails 06-13-2000
    S_SKIM5, // Skim mine dropper Tails 06-13-2000
    S_SKIM6, // Skim mine dropper Tails 06-13-2000
    S_SKIM7, // Skim mine dropper Tails 06-13-2000
    S_SKIM8, // Skim mine dropper Tails 06-13-2000
    S_SKIM9, // Skim mine dropper Tails 06-13-2000
    S_SKIM10, // Skim mine dropper Tails 06-13-2000
    S_SKIM11, // Skim mine dropper Tails 06-13-2000
    S_SKIM12, // Skim mine dropper Tails 06-13-2000
    S_SKIM13, // Skim mine dropper Tails 06-13-2000
    S_SKIM14, // Skim mine dropper Tails 06-13-2000
    S_SKIM15, // Skim mine dropper Tails 06-13-2000
    S_SKIM16, // Skim mine dropper Tails 06-13-2000
    S_SKIM17, // Skim mine dropper Tails 06-13-2000
    S_SKIM18, // Skim mine dropper Tails 06-13-2000
    S_SKIM19, // Skim mine dropper Tails 06-13-2000
    S_SKIM20, // Skim mine dropper Tails 06-13-2000
    S_SKIM21, // Skim mine dropper Tails 06-13-2000
    S_SKIM22, // Skim mine dropper Tails 06-13-2000
    S_SKIM23, // Skim mine dropper Tails 06-13-2000
    S_SKIM24, // Skim mine dropper Tails 06-13-2000
    S_SKIM25, // Skim mine dropper Tails 06-13-2000
    S_SKIM26, // Skim mine dropper Tails 06-13-2000
    S_SKIM27, // Skim mine dropper Tails 06-13-2000
    S_SKIM28, // Skim mine dropper Tails 06-13-2000
    S_SKIM29, // Skim mine dropper Tails 06-13-2000
    S_SKIM30, // Skim mine dropper Tails 06-13-2000
    S_SKIM_BOOM1, // Skim mine dropper explode Tails 06-13-2000
    S_SKIM_BOOM2, // Skim mine dropper explode Tails 06-13-2000
    S_SKIM_BOOM3, // Skim mine dropper explode Tails 06-13-2000
    S_SKIM_BOOM4, // Skim mine dropper explode Tails 06-13-2000
    S_MINE1, // Skim mine Tails 06-13-2000
    S_MINE_BOOM1, // Skim mine explode Tails 06-13-2000
    S_MINE_BOOM2, // Skim mine explode Tails 06-13-2000
    S_MINE_BOOM3, // Skim mine explode Tails 06-13-2000
    S_MINE_BOOM4, // Skim mine explode Tails 06-13-2000
    S_FISH1, // Greenflower Fish Tails 07-03-2000
    S_FISH2, // Greenflower Fish Tails 07-03-2000
    S_FISH3, // Greenflower Fish Tails 07-03-2000
    S_FISH4, // Greenflower Fish Tails 07-03-2000
    S_FISH_DIE1, // Greenflower Fish Tails 07-03-2000
    S_FISH_DIE2, // Greenflower Fish Tails 07-03-2000
    S_FISH_DIE3, // Greenflower Fish Tails 07-03-2000
    S_FISH_DIE4, // Greenflower Fish Tails 07-03-2000
    S_GARGOYLE, // Deep Sea Gargoyle Tails 07-29-2000
	S_SPLISH1, // Tails 12-08-2000
	S_SPLISH2, // Tails 12-08-2000
	S_SPLISH3, // Tails 12-08-2000
	S_SPLISH4, // Tails 12-08-2000
	S_SPLISH5, // Tails 12-08-2000
	S_SPLISH6, // Tails 12-08-2000
	S_SPLISH7, // Tails 12-08-2000
	S_SPLISH8, // Tails 12-08-2000
	S_SPLISH9, // Tails 12-08-2000
    S_GTHOK1, // Tails 12-05-99 Thok! mobj
	S_THZPLANT1, // THZ Plant Tails 12-19-2000
	S_THZPLANT2, // THZ Plant Tails 12-19-2000
	S_THZPLANT3, // THZ Plant Tails 12-19-2000
	S_THZPLANT4, // THZ Plant Tails 12-19-2000
	S_SIGN1, // Level end sign Tails 01-14-2001
	S_SIGN2, // Level end sign Tails 01-14-2001
	S_SIGN3, // Level end sign Tails 01-14-2001
	S_SIGN4, // Level end sign Tails 01-14-2001
	S_SIGN5, // Level end sign Tails 01-14-2001
	S_SIGN6, // Level end sign Tails 01-14-2001
	S_SIGN7, // Level end sign Tails 01-14-2001
	S_SIGN8, // Level end sign Tails 01-14-2001
	S_SIGN9, // Level end sign Tails 01-14-2001
	S_SIGN10, // Level end sign Tails 01-14-2001
	S_SIGN11, // Level end sign Tails 01-14-2001
	S_SIGN12, // Level end sign Tails 01-14-2001
	S_SIGN13, // Level end sign Tails 01-14-2001
	S_SIGN14, // Level end sign Tails 01-14-2001
	S_SIGN15, // Level end sign Tails 01-14-2001
	S_SIGN16, // Level end sign Tails 01-14-2001
	S_SIGN17, // Level end sign Tails 01-14-2001
	S_SIGN18, // Level end sign Tails 01-14-2001
	S_SIGN19, // Level end sign Tails 01-14-2001
	S_SIGN20, // Level end sign Tails 01-14-2001
	S_SIGN21, // Level end sign Tails 01-14-2001
	S_SIGN22, // Level end sign Tails 01-14-2001
	S_SIGN23, // Level end sign Tails 01-14-2001
	S_SIGN24, // Level end sign Tails 01-14-2001
	S_SIGN25, // Level end sign Tails 01-14-2001
	S_SIGN26, // Level end sign Tails 01-14-2001
	S_SIGN27, // Level end sign Tails 01-14-2001
	S_SIGN28, // Level end sign Tails 01-14-2001
	S_SIGN29, // Level end sign Tails 01-14-2001
	S_SIGN30, // Level end sign Tails 01-14-2001
	S_SIGN31, // Level end sign Tails 01-14-2001
	S_SIGN32, // Level end sign Tails 01-14-2001
	S_SIGN33, // Level end sign Tails 01-14-2001
	S_SIGN34, // Level end sign Tails 01-14-2001
	S_SIGN35, // Level end sign Tails 01-14-2001
	S_SIGN36, // Level end sign Tails 01-14-2001
	S_SIGN37, // Level end sign Tails 01-14-2001
	S_SIGN38, // Level end sign Tails 01-14-2001
	S_SIGN39, // Level end sign Tails 01-14-2001
	S_SIGN40, // Level end sign Tails 01-14-2001
	S_SIGN41, // Level end sign Tails 01-14-2001
	S_SIGN42, // Level end sign Tails 01-14-2001
	S_SIGN43, // Level end sign Tails 01-14-2001
	S_SIGN44, // Level end sign Tails 01-14-2001
	S_SIGN45, // Level end sign Tails 01-14-2001
	S_SIGN46, // Level end sign Tails 01-14-2001
	S_SIGN47, // Level end sign Tails 01-14-2001
	S_SIGN48, // Level end sign Tails 01-14-2001
	S_SIGN49, // Level end sign Tails 01-14-2001
	S_SIGN50, // Level end sign Tails 01-14-2001
	S_SIGN51, // Level end sign Tails 01-14-2001
	S_SIGN52, // Level end sign Tails 01-14-2001
	S_RRNG1, // Tails 03-13-2001
	S_RRNG2, // Tails 03-13-2001
	S_RRNG3, // Tails 03-13-2001
	S_RRNG4, // Tails 03-13-2001
	S_RRNG5, // Tails 03-13-2001
	S_RRNG6, // Tails 03-13-2001
	S_RRNG7, // Tails 03-13-2001
	S_RRNG8, // Tails 03-13-2001
	S_TTAG1, // Tails 05-08-2001
	S_STEAM1, // Steam riser Tails 05-28-2001
	S_STEAM2, // Steam riser Tails 05-28-2001
	S_STEAM3, // Steam riser Tails 05-28-2001
	S_STEAM4, // Steam riser Tails 05-28-2001
	S_STEAM5, // Steam riser Tails 05-28-2001
	S_STEAM6, // Steam riser Tails 05-28-2001
	S_STEAM7, // Steam riser Tails 05-28-2001
	S_STEAM8, // Steam riser Tails 05-28-2001
	S_REDFLAG, // Red CTF Flag Tails 07-22-2001
	S_BLUEFLAG, // Blue CTF Flag Tails 07-22-2001
	S_GOTFLAG1, // Got Flag sign Tails 07-22-2001
	S_GOTFLAG2, // Got Flag sign Tails 07-22-2001
	S_GOTFLAG3, // Got Flag sign Tails 07-22-2001
	S_GOTFLAG4, // Got Flag sign Tails 07-22-2001
	S_TOKEN, // Special Stage Token Tails 08-11-2001
	S_TOKEN2, // Special Stage Token Tails 08-17-2001
	S_CEMG, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMO, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMP, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMB, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMR, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEML, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMY, // Chaos Emerald (intangible) Tails 08-18-2001
	S_JETBLOOK1, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBLOOK2, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBZOOM1, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBZOOM2, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBDIE1, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBDIE2, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBDIE3, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBDIE4, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETGLOOK1, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGLOOK2, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGZOOM1, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGZOOM2, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGSHOOT1, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGSHOOT2, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGDIE1, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGDIE2, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGDIE3, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGDIE4, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETBULLET1, // Jetty-Syn Bullet Tails 08-25-2001
	S_JETBULLET2, // Jetty-Syn Bullet Tails 08-25-2001
	S_MOUSE1, // Mouse Tails 08-26-2001
	S_MOUSE2, // Mouse Tails 08-26-2001
	S_DETON1, // Deton Tails 08-26-2001
	S_DETON2, // Deton Tails 08-26-2001
	S_XPLD1, // Robot Explosion Tails 08-26-2001
	S_XPLD2, // Robot Explosion Tails 08-26-2001
	S_XPLD3, // Robot Explosion Tails 08-26-2001
	S_XPLD4, // Robot Explosion Tails 08-26-2001
	S_REDVXI, // RedXVI
	S_CEZCHAIN, // CEZ Chain Tails 11-02-2001
	S_CAPE1, // Fake little Super Sonic cape Tails 11-12-2001
	S_CAPE2, // Fake little Super Sonic cape Tails 11-12-2001
	S_SNOW1, // Snowflake Tails 12-02-2001
	S_SNOW2, // Snowflake Tails 12-02-2001
	S_SNOW3, // Snowflake Tails 12-02-2001
	S_SANTA1, // Santa Tails 12-12-2001
	S_EMER1, // Emerald Hunt 1 Tails 12-12-2001
	S_EMES1, // Emerald Hunt 2 Tails 12-12-2001
	S_EMET1, // Emerald Hunt 3 Tails 12-12-2001
	S_SBLL1, // Snow Ball for Snow Buster Tails 12-12-2001
	S_SBLL2, // Snow Ball for Snow Buster Tails 12-12-2001
	S_SPIKEBALL1, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL2, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL3, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL4, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL5, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL6, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL7, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL8, // Spike Ball Tails 12-18-2001
	S_CCOMMAND1, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND2, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND3, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND4, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND5, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND6, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND7, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND8, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND9, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND10, // Crawla Commander Tails 12-30-2001
	S_AIRPARTICLE,
	S_AIRPARTICLE2,
	S_AIRPARTICLE3,
	S_AIRPARTICLE4,
	S_AIRPARTICLE5,
	S_AIRPARTICLE6,
	S_AIRPARTICLE7,
	S_AIRPARTICLE8,
	S_MARILUNFINISHED,
	S_DUMMY_STND,
	S_RAIN1,
	S_RAINRETURN,
	S_SPRING_VERTI, // new springs! Nozomi 03-28-2026
	S_SPRING_VERTI2,
	S_SPRING_VERTI3,
	S_SPRING_VERTI4,
	S_SPRING_VERTI5,
	S_SPRING_VERTI6,
	S_SPRING_VERTI7,
	S_SPRING_VERTI8,
	S_SPRING_DIAG,
	S_SPRING_DIAG2,
	S_SPRING_DIAG3,
	S_SPRING_DIAG4,
	S_SPRING_DIAG5,
	S_SPRING_DIAG6,
	S_SPRING_DIAG7,
	S_SPRING_DIAG8,
	S_SPRING_HORIZ,
	S_SPRING_HORIZ2,
	S_SPRING_HORIZ3,
	S_SPRING_HORIZ4,
	S_SPRING_HORIZ5,
	S_SPRING_HORIZ6,
	S_SPRING_HORIZ7,
	S_SPRING_HORIZ8,
    NUMSTATES
} statenum_t;


typedef struct
{
  spritenum_t   sprite;
  long          frame;          //faB: we use the upper 16bits for translucency
                                //     and other shade effects
  long          tics;
  // void       (*action) ();
  actionf_t     action;
  statenum_t    nextstate;
//  long          misc1, misc2;
} state_t;


extern state_t  states[NUMSTATES];
extern char *sprnames[NUMSPRITES+1];



typedef enum {
    MT_PLAYER,
    MT_BLUECRAWLA,
    MT_REDCRAWLA,
    MT_EGGMOBILE,
    MT_ROCKET,
    MT_TELEPORTMAN,
    MT_MISC2,
    MT_MISC10,
    MT_MISC11,
    MT_EMMY, // emerald tails
    MT_INV,
    MT_MISC31,
    MT_MISC34,
	MT_REDFAN,
    MT_BUBBLES, // Bubble source Tails 03-07-2000
    MT_MISC37,
    MT_MISC48,
    MT_MISC50,
    MT_MISC70,
    MT_MISC74,
    MT_MISC84,
    MT_CHASECAM,
    MT_SPIRIT,
    MT_SMOK,        // test lave/slime damage smoke
    MT_SPLASH,      // test water splash
    MT_PUSH,    //SoM: 3/8/2000: controls push source
    MT_PULL,    //SoM: 3/8/2000: controls pull source
	MT_FLINGRING,   //SOM: Test rings flying
    MT_BIRD, // Tails 10-20-99 Birdie freed!
    MT_SQRL, // Tails 10-20-99 Squirrel freed!
    MT_BLUEORB, // Tails 12-29-99 shield mobjs
    MT_YELLOWORB, // Tails 12-29-99 shield mobjs
    MT_GREENORB, // Tails 12-29-99 shield mobjs
    MT_BLACKORB, // Tails 12-29-99 shield mobjs
    MT_SPARK, //spark tails
    MT_IVSP, // invincibility sparkles tails
    MT_IVSQ, // invincibility sparkles finish tails
    MT_DISS, // dissipating object tails
    MT_SMALLBUBBLE, // small bubble Tails 03-07-2000
    MT_MEDIUMBUBBLE, // medium bubble Tails 03-07-2000
    //MT_LARGEBUBBLE, // large bubble Tails 03-07-2000
    MT_EXTRALARGEBUBBLE, // extra large bubble Tails 03-07-2000
    MT_ZERO, // Drowning Timer - 0 Tails 03-07-2000
    MT_ONE, // Drowning Timer - 1 Tails 03-07-2000
    MT_TWO, // Drowning Timer - 2 Tails 03-07-2000
    MT_THREE, // Drowning Timer - 3 Tails 03-07-2000
    MT_FOUR, // Drowning Timer - 4 Tails 03-07-2000
    MT_FIVE, // Drowning Timer - 5 Tails 03-07-2000
    MT_POP, // Extra Large bubble goes POP! Tails 03-08-2000
    MT_PRUP, // 1up Box Tails 03-12-2000
    MT_BKTV, // Black shield TV Tails 04-08-2000
    MT_SCRA, // 100 score logo Tails 04-16-2000
    MT_SCRB, // 200 score logo Tails 04-16-2000
    MT_SCRC, // 500 score logo Tails 04-16-2000
    MT_SCRD, // 1000 score logo Tails 04-16-2000
    MT_SUPERSPARK, // Super Sonic Spark Tails 04-18-2000
    MT_GRASSDEBRIS, // Grass debris Tails 05-14-2000
    MT_YELLOWDIAG, // Yellow Diagonal Spring Tails 05-17-2000
    MT_AWATERA, // Ambient Water Sound 1 Tails 06-10-2000
    MT_AWATERB, // Ambient Water Sound 2 Tails 06-10-2000
    MT_AWATERC, // Ambient Water Sound 3 Tails 06-10-2000
    MT_AWATERD, // Ambient Water Sound 4 Tails 06-10-2000
    MT_AWATERE, // Ambient Water Sound 5 Tails 06-10-2000
    MT_AWATERF, // Ambient Water Sound 6 Tails 06-10-2000
    MT_AWATERG, // Ambient Water Sound 7 Tails 06-10-2000
    MT_AWATERH, // Ambient Water Sound 8 Tails 06-10-2000
    MT_SKIM, // Skim mine dropper Tails 06-13-2000
    MT_MINE, // Skim mine Tails 06-13-2000
    MT_GFZFISH, // Greenflower Fish Tails 07-03-2000
    MT_GARGOYLE, // Deep Sea Gargoyle Tails 07-29-2000
	MT_SPEEDPAD, // "speed pad" Tails 12-01-2000
	MT_SPLISH, // Water splish! Tails 12-08-2000
    MT_THOK, // Tails 12-05-99 Thok! mobj // Nozomi 03-12-2026 Rid of the other thok mobjs thanks to transtransfunc!!! :3333 
	MT_THZPLANT, // THZ Plant Tails 12-19-2000
	MT_SIGN, // Level end sign Tails 01-14-2001
	MT_REDRING, // Tails 03-13-2001
	MT_TAG, // Tag Sign Tails 05-08-2001
	MT_STEAM, // Steam riser Tails 05-28-2001
	MT_REDFLAG, // Red CTF Flag Tails 07-22-2001
	MT_BLUEFLAG, // Blue CTF Flag Tails 07-22-2001
	MT_GOTFLAG, // Got Flag sign Tails 07-22-2001
	MT_GOTFLAG2, // Got Flag sign Tails 08-02-2001
	MT_TOKEN, // Special Stage Token Tails 08-11-2001
	MT_GREENEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_ORANGEEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_PINKEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_BLUEEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_REDEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_LIGHTBLUEEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_GREYEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_JETTBOMBER, // Jetty-Syn Bomber Tails 08-18-2001
	MT_JETTGUNNER, // Jetty-Syn Gunner Tails 08-25-2001
	MT_JETTBULLET, // Jetty-Syn Bullet Tails 08-25-2001
	MT_MOUSE, // Mouse Tails 08-26-2001
	MT_DETON, // Deton Tails 08-26-2001
	MT_EXPLODE, // Robot Explosion Tails 08-26-2001
	MT_REDVXI, // RedVXI
	MT_CHAIN, // CEZ Chain Tails 11-02-2001
	MT_CAPE, // Fake little Super Sonic cape Tails 11-12-2001
	MT_SNOWFLAKE, // Snowflake Tails 12-02-2001
	MT_SANTA, // Santa Tails 12-12-2001
	MT_EMERHUNT, // Emerald Hunt 1 Tails 12-12-2001
	MT_EMESHUNT, // Emerald Hunt 2 Tails 12-12-2001
	MT_EMETHUNT, // Emerald Hunt 3 Tails 12-12-2001
	MT_SNOWBALL, // Snow Ball for Snow Buster Tails 12-12-2001
	MT_SPIKEBALL, // Spike Ball Tails 12-18-2001
	MT_CRAWLACOMMANDER, // Crawla Commander Tails 12-30-2001
	MT_AIRPARTICLE,
	MT_AIRPARTICLE2,
	MT_AIRPARTICLE3,
	MT_AIRPARTICLE4,
	MT_MARILUNFINISHED,
	MT_RAIN,
	MT_NOZOMI_YSPRING,
	MT_NOZOMI_RSPRING,
	MT_NOZOMI_BSPRING,
	MT_NOZOMI_YDIAGSPRING,
	MT_NOZOMI_RDIAGSPRING,
	MT_NOZOMI_BDIAGSPRING,
	MT_NOZOMI_YHORIZSPRING,
	MT_NOZOMI_RHORIZSPRING,
	MT_NOZOMI_BHORIZSPRING,
    NUMMOBJTYPES

} mobjtype_t;

typedef struct
{
    int doomednum;
    int spawnstate;
    int spawnhealth;
    int seestate;
    int seesound;
    int reactiontime;
    int attacksound;
    int painstate;
    int painchance;
    int painsound;
    int meleestate;
    int missilestate;
    int deathstate;
    int xdeathstate;
    int deathsound;
    int speed;
    int radius;
    int height;
    int mass;
    int damage;
    int activesound;
    int flags;
    int raisestate;
	int flags2;
} mobjinfo_t;

extern mobjinfo_t mobjinfo[NUMMOBJTYPES];

#endif
